meta_title: "CforGood - La Révolution Positive"
meta_description: "CforGood est une plateforme qui redonne le pouvoir d'agir dans le bon sens en nous connectant aux acteurs positifs du territoire pour favoriser les comportements responsables !"
meta_image: "default-meta-image.jpg"
twitter_account: "@CforGood"